//PROPERTIES

#SPRING
spring.datasource.url=jdbc:mysql://localhost:3306/hoyjugasDB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.servlet.context-path=/hoyjugas
spring.jpa.properties.hibernate.type.preferred_set_type=varchar

#JWT
jwt.secret=qW8H7v+fVtP1e3R2iK9N6J8xYgR4lO2qE3vK7sL0hP5dF1gH2jK4mN8pR0sV6tX9qW8H7v+fVtP1e3R2iK9N6J8xYgR4lO2qE3vK7sL0hP5dF1gH2jK4mN8pR0sV6tX9
jwt.expiration=100000000

#MERCADO PAGO, ACTUALIZAR TODO DESPUES EN DEPLOY
mp.access.token=APP_USR-3625320956981711-060123-2dd5acde585d64ecfb48479f50f10f28-3442108147
mp.public.key=APP_USR-fcd291c8-1f45-48ac-a3a9-75452719c341
mp.success.url=http://localhost:4200/booking/success
mp.failure.url=http://localhost:4200/booking/failure
mp.pending.url=http://localhost:4200/booking/pending
mp.webhook.url=https://passage-traps-unskilled.ngrok-free.dev/hoyjugas/webhooks/mp
mp.webhook.secret=faee42e8b292cde0b700aa59d959712476231fd037eac272db14758c86ad68c5

#GMAIL
gmail.credentials.path=credentials/credentials.json

#TWILIO, ACTUALIZAR DESPUES EN DEPLOY
twilio.account.sid=ACefc41310ac0481f3e1b9d4a5b66a090d
twilio.auth.token=fae4813a9de91c835a294f7118a31ede
twilio.whatsapp.from=whatsapp:+14155238886
#prototipado por las dudas, dsps sacar porque no se usa
twilio.whatsapp.to=whatsapp:+5492236352149

#PUERTO
server.port=8080